package dynamic

import (
	"time"

	runtimedynamic "github.com/Phala-Network/phala-inference-guard/internal/runtime/dynamic"
)

func buildCleanSnapshot(cfg Config, input Input, nowTime time.Time, result cleanPipelineResult) runtimedynamic.Snapshot {
	signals := result.Signals
	ttft := result.TTFT
	throughput := result.Throughput
	limits := result.Limits
	return runtimedynamic.Snapshot{
		Enabled:                    cfg.Enabled,
		Enforce:                    cfg.Enforce,
		Decision:                   limits.Decision,
		State:                      limits.Decision.State,
		Source:                     "metrics",
		Updated:                    nowTime,
		Running:                    signals.Running,
		Waiting:                    signals.Waiting,
		KVCacheUsage:               signals.KVCacheUsage,
		Preemptions:                signals.Preemptions,
		Generation:                 signals.Generation,
		GenerationTPS:              signals.GenerationTPS,
		GenerationTPSValid:         signals.GenerationTPSValid,
		TTFTCumulative:             signals.Aggregated.TTFT,
		SemanticTTFTCumulative:     ttft.SemanticCumulative,
		TTFTSource:                 ttft.Source,
		TTFTWindowCount:            ttft.Observation.Count,
		TTFTWindowAvg:              ttft.Observation.Avg,
		TTFTWindowP95:              ttft.Observation.P95,
		TTFTWindowP99:              ttft.Observation.P99,
		TTFTWindowValid:            ttft.Observation.Valid,
		TTFTSmoothedAvg:            ttft.Observation.SmoothedAvg,
		TTFTSmoothedP95:            ttft.Observation.SmoothedP95,
		TTFTSmoothedP99:            ttft.Observation.SmoothedP99,
		TTFTHighCount:              ttft.Assessment.HighCount,
		TTFTP99HighCount:           ttft.Assessment.TailHighCount,
		TTFTHealthyCount:           ttft.Assessment.HealthyCount,
		TTFTLearnState:             ttft.State,
		TTFTLearnReason:            ttft.Reason,
		TTFTTargetReason:           ttft.TargetReason,
		TTFTLearnedLimit:           ttft.LearnedLimit,
		TTFTTargetLimit:            ttft.TargetLimit,
		TTFTLimit:                  ttft.Limit,
		CapacityTPS:                signals.CapacityTPS,
		CapacityRatio:              cfg.CapacityRatio,
		CapacityRatioHealthyCount:  throughput.Result.HealthyCount,
		CapacityRawLimit:           signals.CapacityEstimate.RawLimit,
		CapacitySafeLimit:          signals.CapacityEstimate.SafeLimit,
		CapacityLowConfidenceLimit: signals.CapacityEstimate.LowConfidenceLimit,
		CapacityEstimateConfidence: signals.CapacityEstimate.Confidence,
		CapacityRepresentativeLoad: signals.CapacityEstimate.RepresentativeLoad,
		CapacityLearnMode:          "clean_cap",
		CapacityLearnState:         throughput.Result.State,
		CapacityLearnReason:        throughput.Result.Reason,
		CapacityTargetReason:       throughput.Result.TargetReason,
		CapacityProjectedLimit:     throughput.Result.ProjectedLimit,
		CapacityLearnedLimit:       throughput.Result.LearnedLimit,
		CapacityTargetLimit:        throughput.Result.TargetLimit,
		CapacityLimit:              limits.CapacityLimit,
		HardGlobalLimit:            limits.HardGlobalLimit,
		StateLimit:                 limits.StateLimit,
		ThroughputLimit:            limits.ThroughputLimit,
		AvailabilityLimit:          limits.AvailabilityLimit,
		UserTPS:                    signals.UserTPS,
		UserTPSYellowCount:         signals.UserTPSYellowCount,
		UserTPSRedCount:            signals.UserTPSRedCount,
		PrefillProtected:           signals.PrefillProtected,
		PrefillTransition:          signals.PrefillTransition,
		PrefillSettling:            signals.PrefillSettling,
		PrefillLimit:               limits.PrefillLimit,
		PrefillReason:              result.Prefill.Reason,
		PrefillTargetReason:        result.Prefill.TargetReason,
		DecodeRunning:              signals.DecodeRunning,
		QOSLimit:                   limits.QOSLimit,
		RepresentativeUserTPSLoad:  signals.RepresentativeUserTPSLoad,
		PressureLimit:              limits.PressureLimit,
		PressureReason:             result.Pressure.Reason,
		PressureTargetReason:       result.Pressure.TargetReason,
		BackendCount:               signals.BackendCount,
		BackendFailed:              input.BackendFailed,
		DynamicRejected:            signals.DynamicRejected,
		DynamicRejectedDelta:       signals.DynamicRejectedDelta,
		TierBasicRejected:          signals.TierBasicRejected,
		TierPremiumRejected:        signals.TierPremiumRejected,
		TierBasicRejectedDelta:     signals.TierBasicRejectedDelta,
		TierPremiumRejectedDelta:   signals.TierPremiumRejectedDelta,
		TierBasicWaiting:           signals.TierBasicWaiting,
		TierPremiumWaiting:         signals.TierPremiumWaiting,
		TierDemandPressure:         signals.TierDemandPressure,
		CapacityDemandPressure:     signals.CapacityDemandPressure,
		GlobalLimit:                limits.FinalLimit,
		FinalLimitReason:           limits.FinalLimitReason,
		YellowReasons:              limits.Decision.YellowReasons,
		RedReasons:                 limits.Decision.RedReasons,
	}
}
