package pigconfig

import "time"

type Backend struct {
	Name       string
	Upstream   string
	MetricsURL string
}

type Config struct {
	Listen                           string
	Upstream                         string
	Backends                         []Backend
	BackendRouting                   bool
	Token                            string
	QoSPaths                         []string
	APIAuthEnabled                   bool
	APIAuthPaths                     []string
	PathSuffixMatch                  bool
	GlobalLimit                      int
	OpenAICompatStripEmptyToolCalls  bool
	OpenAICompatBodyBytes            int64
	OpenAICompatFailOpen             bool
	AttestationEnabled               bool
	AttestationDstackEndpoint        string
	AttestationTLSCertPath           string
	AttestationGPUArch               string
	AttestationNVIDIAPayload         string
	AttestationNVIDIAPayloadFile     string
	AttestationNVIDIAPayloadURL      string
	AttestationNVIDIAPayloadAuth     string
	AttestationNVIDIACommand         string
	AttestationNVIDIACommandArgs     []string
	AttestationNVIDIACommandTimeout  time.Duration
	AttestationRequireNVIDIAEvidence bool
	ClassifyOutputTokens             bool
	JSONClassifyBodyBytes            int64
	JSONClassifyLimit                int
	OutputTokenFields                []string
	MediumBodyBytes                  int64
	LongBodyBytes                    int64
	VeryLongBodyBytes                int64
	MediumOutputTokens               int
	LongOutputTokens                 int
	VeryLongOutputTokens             int
	AdaptiveOutput                   bool
	AdaptiveOutputWindow             int
	AdaptiveOutputMin                int
	AdaptiveOutputMediumQ            float64
	AdaptiveOutputLongQ              float64
	AdaptiveOutputVeryQ              float64
	AdaptiveOutputGreen              float64
	AdaptiveOutputYellow             float64
	AdaptiveOutputRed                float64
	BackendPriorityInjectionEnabled  bool
	BackendPriorityMode              string
	BackendPriorityRewriteStrategy   string
	BackendPriorityField             string
	BackendPriorityPremiumValue      int
	BackendPriorityBasicValue        int
	BackendPriorityBodyBytes         int64
	BackendPriorityBufferBytes       int64
	BackendPriorityStreamBufferBytes int
	BackendPriorityRewriteLimit      int
	BackendPriorityFailOpen          bool
	DynamicEnabled                   bool
	DynamicEnforce                   bool
	DynamicMetricsURL                string
	DynamicMetricsURLs               []string
	DynamicPollInterval              time.Duration
	DynamicFailsafeState             string
	DynamicKVYellow                  float64
	DynamicKVRed                     float64
	DynamicRunningYellow             int
	DynamicRunningRed                int
	DynamicWaitingYellow             int
	DynamicWaitingRed                int
	DynamicPreemptRed                uint64
	DynamicPressureEnabled           bool
	DynamicPressureHeadroom          int
	DynamicPressureMinLimit          int
	DynamicPressureLearnRatio        float64
	DynamicPressureLearnMinRunning   int
	DynamicUserTPSEnabled            bool
	DynamicTTFTEnabled               bool
	DynamicUserTPSYellow             float64
	DynamicUserTPSRed                float64
	DynamicUserTPSMinRun             int
	DynamicUserTPSYellowN            int
	DynamicUserTPSRedN               int
	DynamicUserTPSGraceMin           time.Duration
	DynamicUserTPSGraceMax           time.Duration
	DynamicUserTPSGraceBps           float64
	DynamicUserTPSGraceMul           float64
	DynamicUserTPSCapacityRatio      float64
	DynamicUserTPSCapacitySmoothing  float64
	DynamicUserTPSCapacityLearn      bool
	DynamicUserTPSCapacityRatioMax   float64
	DynamicUserTPSCapacityStepUp     float64
	DynamicUserTPSCapacityHealthyN   int
	DynamicUserTPSCapacityHealthyMul float64
	DynamicGlobalGreen               int
	DynamicGlobalYellow              int
	DynamicGlobalRed                 int
	SSEKeepAliveEnabled              bool
	SSEEarlyBridgeEnabled            bool
	ProxyTimeout                     time.Duration
	StatusLogInterval                time.Duration
	QoSQueueWait                     time.Duration
	QoSQueuePoll                     time.Duration
}
